### ISSUE TITLE
Bug ao cadastrar ponto

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/controle-ponto#38]
Cenário: 
- Clicar em adicionar ponto;
- selecionar uma data;
- digitar um horário inválido (por exemplo: 09)
- tentar enviar
- Corrigir o horário (máscara não pega)
- Horário corrigido (Erro na validação)

**Comment by edumaxsantos** [comment]
Opa, fiz um teste aqui e troquei uma coisa no seu oninvalid.
Onde estava:
`oninvalid="this.setCustomValidity('Por favor, digitar um valor válido')"`
Coloquei assim:
`oninvalid="this.setCustomValidity(this.willValidate? '':'Por favor, digitar um valor válido')"`
e a validação foi aceita após corrigida.

**Comment by raulfdm** [comment]
Opa... vou aplicar! Muito obrigado @edumaxsantos
