### ISSUE TITLE
Adicionar o evento de remoção do ponto

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/controle-ponto#4]
O evento deverá ser o double-click e deverá abrir um modal para confirmar o delete.

**Comment by ghost** [comment]
Só por curiosidade, você não vai implementar nada em cima de double-click certo?
Pergunto porquê isso é um anti-pattern, nada na web se comporta em torno de clique duplo.
Clique duplo é um comportamento esperado apenas no sistema operacional quando o usuário está executando um programa ou abrindo arquivos, na web esse conceito desaparece e aparece o clique simples, no máximo o clique com o botão direito para exibir um menu de contexto personalizado em aplicações mais complexas/robustas como o google docs.

**Comment by raulfdm** [comment]
@wesleycoder , a intenção era sim! hahahaha Mas, vou trocar para ser onclick. Eu tive a ideia do double click porque eu ainda não fiz o modal, e no click ia ficar muito fácil errar. Mas, obrigado pela dica!

**Comment by raulfdm** [comment]
Implementação realizada no commit 0cd5035103e2e7c237a54af50b92a90e07a34ac8

**Comment by ghost** [comment]
Só por conhecimento você pode fechar uma issue no github adicionando `Closes #4` na mensagem de commit ([fonte](https://help.github.com/articles/closing-issues-via-commit-messages/)).
